name: "Dev DEPLOY"

on:
    push:
        branches:
            - develop    
permissions:
      id-token: write
      contents: read 

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            aws-assume-role-arn: "arn:aws:iam::699475947366:oidc-provider/token.actions.githubusercontent.com"
            aws-region: "us-east-1"
            aws-statefile-s3-buchet: "github-terraform-joaovictorlong"
            aws-lock-dynamodb-table: "github-terraform-joaovictorlong"