name: "Dev DEPLOY"

on:
    push:
        branches:
            - develop    
permissions:
      id-token: write
      contents: read 

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            aws-assume-role-arn: "arn:aws:iam::699475947366:role/gitHub-Actions-Terraform"
            aws-region: "us-east-1"
            aws-state-file-s3-bucket: "github-terraform-joaovictorlong"
            aws-lock-dynamodb-table: "github-terraform-joaovictorlong"